### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by gsmedley** [imgurbot12/pypub#15]
When I start with HTML something like this:

```
<h2>Table</h2>
<table>
  <tr>
    <td>Cell one</td>
    <td>Cell two</td>
  </tr>
  <tr>
    <td>Cell three</td>
    <td>cell four</td>
  </tr>
</table>
```

I end up with 

```
  <body>
    <h2>Table</h2>
    <p><br/>
    </p>
    <hr/>
  </body>
```

**Comment by imgurbot12** [comment]
This is likely because table is not listed as one of the supported tags when cleaning up existing html:
https://github.com/imgurbot12/pypub/blob/master/pypub/factory.py#L42

The list of supported tags is a carry over from the original library implementation which also does not include tables:
https://github.com/wcember/pypub/blob/master/pypub/constants.py#L3
I assumed this meant tables were not supported in epub but that is apparently not the case. Working to include them in the next update. Thanks!

**Comment by imgurbot12** [comment]
Just merged another PR with fixes to support table/th/tr/td tags. Pushed to pypi under `2.0.4`. Please update and let me know how it goes for you. Thanks again for helping resolve issues like this :)

**Comment by gsmedley** [comment]
Working now, thanks!
