### ISSUE TITLE
Inline styles

### ISSUE THREAD

**Issue by gsmedley** [imgurbot12/pypub#18]
I have HTML that sets font size and text color using an inline style, but it doesn't make it to the EPUB. 

```
<p style="color:blue; font-size:12px;">This is a paragraph.</p>
```

Similarly for list items:

```
<ol style="list-style-type: lower-alpha;"><li>​a list item</li></ol>
```

Should style attrs just be passed through unchanged? With the understanding that some may be ignored by some readers.

**Comment by imgurbot12** [comment]
Apologies for the delay in response. 
Thank you for your patience.

At the moment the library is very selective with what attributes and tags it allows since that was the logic carried over from the original before the fork and rewrite. I assumed this was because the epub standard was much more particular about what is allowed in xhtml than normal html. I've tried to do some research on the topic to discover what is allowed and what is not but I've yet to find anything specifically about this yet.

For the sake of backwards compatibility/cleanliness/control I hesitate to add support for any and all tags or try to reverse the behavior into a blacklist rather than the current whitelisted system, so for the time being I'm simply going to recommend either monkeypatching the library itself or finding alternatives by replacing the inline styles with standard css.

Inline styles are a bit tricky for me to determine how to handle because I can see wanting to keep those styles when importing html into an epub, but at the same time, being able to automatically remove inline styles and instead replace them with your own css seems valuable and like a good approach as well.

You can monkeypatch the library by doing something like the following:
```python
from pypub.factory import SUPPORTED_TAGS
SUPPORTED_TAGS['p'] = (*SUPPORTED_TAGS['p'], 'style')
```

I'm happy to hear arguments or alternative opinions about what I've said here if you happen to know more about the epub standard or have suggestions about an alternative approach for implementation. PRs are always welcome as well :)

Hope that helps!

**Comment by gsmedley** [comment]
Thanks for the thoughtful response. I agree it's better not to break existing functionality, and great that there is way to override the defaults. I'll give that a try.
