### ISSUE TITLE
Getting an error trying to run the exemple code

### ISSUE THREAD

**Issue by SenCoquecigrues** [imgurbot12/pypub#7]
Hi! When trying to run the example code, I get the following error, which seems to be tied to xml parsing:
"epub ValueError: ('unsupported token', Result(token=<XToken.FUNCTION: 8>, value=b'text()', lineno=0, position=9))"

Is the module perhaps incompatible with python 3.10?

Thank you very much for your hard work anyway!

**Comment by imgurbot12** [comment]
@SenzenTravers Hello! Apologies for the slow response. Your Issue didn't show up in my notifications for some reason. That looks like it might be related to the new html parser I've implemented. Would you be able to tell me a bit more about the issue?

If you can tell me what html-file/url were you downloading I might be able to replicate your problem and make a hotfix for it.

**Comment by imgurbot12** [comment]
@SenzenTravers, apologies again. I've come back and read your question again and realized you were talking about the README example.

I recently migrated away from lxml to use my own xml/html parser I've build in pure python and was hoping to use pypub as a testing ground for some of it's new features. It had worked for my spacebattles example I included in this repo, but as it turns out I didn't test it thoroughly enough since it broke nearly everywhere else lol.

I've just completed a [massive series of patches to pyxml](https://github.com/imgurbot12/pyxml/pull/7) that should fix any issues moving forward, but do please feel free to open another issue here or in the [pyxml](https://github.com/imgurbot12/pyxml) if you're having trouble again.

I've just released a new version of pyxml to pypi. So if you do a `pip install pyxml3 -U`, pypub should begin working again.
Hope that helps. Thanks!

**Comment by SenCoquecigrues** [comment]
Hello, @imgurbot12 ! Sorry I was late to answer. Thank you very much for the patch and for this wonderful tool!
